"use client";

/**
 * The verdict, rendered as the dominant element on the page. The headline
 * label is derived from the AI's own category — it is never hardcoded per
 * scenario.
 */
const STYLES = {
  FLAKY_TIMING: {
    label: "Likely flaky test",
    tone: "border-amber-300 bg-amber-50",
    accent: "text-amber-900",
    chip: "bg-amber-200 text-amber-900",
    icon: "◐",
  },
  PRODUCT_DEFECT: {
    label: "Likely product defect",
    tone: "border-rose-300 bg-rose-50",
    accent: "text-rose-900",
    chip: "bg-rose-200 text-rose-900",
    icon: "●",
  },
  TEST_DEFECT: {
    label: "Likely test defect",
    tone: "border-violet-300 bg-violet-50",
    accent: "text-violet-900",
    chip: "bg-violet-200 text-violet-900",
    icon: "◆",
  },
  ENVIRONMENT_INFRA: {
    label: "Likely environment issue",
    tone: "border-sky-300 bg-sky-50",
    accent: "text-sky-900",
    chip: "bg-sky-200 text-sky-900",
    icon: "▲",
  },
  INSUFFICIENT_EVIDENCE: {
    label: "Not enough evidence",
    tone: "border-slate-300 bg-slate-100",
    accent: "text-slate-800",
    chip: "bg-slate-300 text-slate-800",
    icon: "○",
  },
};

const BAND_LABEL = { HIGH: "High", MEDIUM: "Medium", LOW: "Low" };

export default function VerdictBanner({ verdict, cached, provenance }) {
  const style = STYLES[verdict.category] || STYLES.INSUFFICIENT_EVIDENCE;
  const band = BAND_LABEL[verdict.confidenceBand] || "Low";
  const model = provenance && provenance.model;

  return (
    <section className={`rounded-2xl border-2 p-6 shadow-sm ${style.tone}`}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs font-semibold uppercase tracking-widest text-slate-500">
          Verdict
        </span>
        {model ? (
          <span className="rounded-full bg-white/70 px-2.5 py-0.5 text-[11px] font-medium text-slate-600">
            {cached ? "Captured from" : "Generated by"} {model}
          </span>
        ) : null}
        {cached ? (
          <span className="rounded-full bg-white/70 px-2.5 py-0.5 text-[11px] font-medium text-slate-600">
            Cached — live call unavailable
          </span>
        ) : null}
      </div>

      <div className="mt-2 flex flex-wrap items-center gap-4">
        <h2 className={`text-3xl font-extrabold tracking-tight sm:text-4xl ${style.accent}`}>
          <span className="mr-2" aria-hidden="true">
            {style.icon}
          </span>
          {style.label}
        </h2>
        <span
          className={`rounded-full px-3 py-1 text-sm font-semibold ${style.chip}`}
        >
          Confidence: {band}
        </span>
      </div>

      <p className={`mt-4 max-w-3xl text-lg leading-relaxed ${style.accent}`}>
        {verdict.headline}
      </p>

      {verdict.rootCause && verdict.rootCause.statement ? (
        <p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-700">
          {verdict.rootCause.statement}
        </p>
      ) : null}

      {verdict.confidenceRationale ? (
        <p className="mt-3 text-sm text-slate-600">
          <span className="font-medium">Why this confidence:</span>{" "}
          {verdict.confidenceRationale}
        </p>
      ) : null}
    </section>
  );
}
