import { loadDashboard } from "@/lib/suite.js";

export const metadata = {
  title: "Full Report — VERDICT",
  description:
    "The complete, unmodified playwright-flaky-analyzer HTML report for the analysed run window.",
};

const REPORT_URL = "/analyzer-report/index.html";

/**
 * The analyzer's own report, served byte-identical from public/. It is embedded
 * rather than reimplemented so a judge sees exactly what the published npm
 * package emits — nothing about it is rewritten by this app.
 */
export default async function ReportPage() {
  const dashboard = await loadDashboard();
  const dataset = dashboard && dashboard.dataset;

  return (
    <div className="space-y-4">
      <a
        href="/flaky"
        className="inline-block text-sm text-slate-500 underline-offset-4 hover:text-slate-900 hover:underline"
      >
        ← Flaky Analysis
      </a>

      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="max-w-2xl">
          <h1 className="font-display text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
            Full analyzer report
          </h1>
          <p className="mt-2 leading-relaxed text-slate-600">
            The complete report generated by{" "}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">
              playwright-flaky-analyzer
            </code>
            {dataset
              ? ` — all ${dataset.tests} tracked tests across ${dataset.runs} runs and ${dataset.executions.toLocaleString("en-GB")} executions,`
              : " —"}{" "}
            exactly as the published package emits it. Nothing on this page is rewritten by
            VERDICT.
          </p>
        </div>

        <a
          href={REPORT_URL}
          target="_blank"
          rel="noreferrer"
          className="flex-none rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-slate-700"
        >
          Open in new tab ↗
        </a>
      </div>

      <div className="overflow-hidden rounded-2xl border border-slate-300 bg-white">
        <iframe
          src={REPORT_URL}
          title="Full playwright-flaky-analyzer report"
          className="h-[calc(100vh-16rem)] min-h-[600px] w-full"
        />
      </div>

      <p className="text-xs text-slate-500">
        This is the same self-contained HTML file the analyzer writes to disk. If the frame
        above is awkward on a small screen, open it in its own tab.
      </p>
    </div>
  );
}
