"use strict";

const { buildInvestigationPrompt } = require("./investigation-prompt");
const { buildInvestigationJsonPrompt } = require("./investigation-json-prompt");

/**
 * Build the AI investigation request for the full analysis report.
 * Returns a single prompt covering the entire suite.
 *
 * @param {Object} analysis - Full analyzer result from analyzer/engine.js compare()
 * @returns {{ prompt: string, analysis: Object }}
 */
function buildAIInvestigationRequest(analysis) {
  return {
    prompt: buildInvestigationPrompt(analysis),
    analysis: analysis,
  };
}

/**
 * Format the investigation prompt as a self-contained markdown file.
 *
 * @param {Object} analysis - Full analyzer result
 * @returns {string} Complete markdown string for investigation-prompt.md
 */
function formatInvestigationPromptMd(analysis) {
  var summary = analysis.summary || {};
  var problematic = (analysis.results || []).filter(function (t) {
    return t.classification !== "stable_pass";
  });
  var flakyCount = summary.flaky || 0;
  var regressionCount = summary.regression || 0;
  var stableFailCount = summary.stable_failure || 0;
  var newlyFailedCount = summary.newly_failed || 0;

  var lines = [];

  lines.push("# AI Investigation Prompt");
  lines.push("");

  lines.push("This prompt was automatically generated by the Playwright Flaky Reporter.");
  lines.push("");
  lines.push("The reporter has already performed deterministic analysis including:");
  lines.push("");
  lines.push("- Flaky detection");
  lines.push("- Failure classification");
  lines.push("- Retry analysis");
  lines.push("- Browser analysis");
  lines.push("- Stability scoring");
  lines.push("- Historical trends");
  lines.push("- Rule-based investigation");
  lines.push("");

  if (problematic.length > 0) {
    var details = [];
    if (flakyCount > 0) details.push(flakyCount + " flaky");
    if (regressionCount > 0) details.push(regressionCount + " regression(s)");
    if (stableFailCount > 0) details.push(stableFailCount + " stable failure(s)");
    if (newlyFailedCount > 0) details.push(newlyFailedCount + " newly failed");
    lines.push(
      "It identified **" +
        problematic.length +
        " problematic test(s)**: " +
        details.join(", ") +
        "."
    );
    lines.push("");
  } else {
    lines.push("It found **0 problematic tests** — all tests are stable.");
    lines.push("");
  }

  lines.push(
    "Paste the prompt below into Claude, GitHub Copilot, Gemini, Azure OpenAI, or another"
  );
  lines.push("LLM to generate an explainable Root Cause Analysis.");
  lines.push("");
  lines.push("---");
  lines.push("");

  if (problematic.length === 0) {
    lines.push("✅ No problematic tests to investigate. The suite is healthy.");
    return lines.join("\n");
  }

  lines.push("## Prompt");
  lines.push("");
  lines.push("Copy everything below this line:");
  lines.push("");
  lines.push("```");
  lines.push(buildInvestigationPrompt(analysis));
  lines.push("```");
  lines.push("");

  // Append the full analysis JSON for reference
  lines.push("---");
  lines.push("");
  lines.push("## Reference: Complete Deterministic Analysis");
  lines.push("");
  lines.push("The full analysis JSON is included below for manual reference.");
  lines.push("The prompt above already contains a focused subset.");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(buildAnalysisReference(analysis), null, 2));
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

/**
 * Format the JSON investigation prompt as a self-contained markdown file.
 * Saves as investigation-json-prompt.md — the AI output is expected to be
 * saved as ai-investigation.json and fed back via --ai-investigation.
 *
 * @param {Object} analysis - Full analyzer result
 * @returns {string} Complete markdown string for investigation-json-prompt.md
 */
function formatInvestigationJsonPromptMd(analysis) {
  var summary = analysis.summary || {};
  var problematic = (analysis.results || []).filter(function (t) {
    return t.classification !== "stable_pass";
  });

  var lines = [];

  lines.push("# AI Investigation JSON Prompt");
  lines.push("");

  lines.push("This prompt was automatically generated by the Playwright Flaky Reporter.");
  lines.push("");
  lines.push("## Purpose");
  lines.push("");
  lines.push("This prompt instructs the AI to return ONLY valid JSON that can be");
  lines.push("fed directly back into the HTML dashboard:");
  lines.push("");
  lines.push("```");
  lines.push(
    "npx playwright-flaky-analyzer analyze ./reports --ai-investigation ai-investigation.json"
  );
  lines.push("```");
  lines.push("");

  if (problematic.length > 0) {
    lines.push(
      "It identified **" +
        problematic.length +
        " problematic test(s)** across " +
        (summary.runsAnalyzed || 0) +
        " runs."
    );
    lines.push("");
  } else {
    lines.push("✅ No problematic tests. All tests are stable.");
    return lines.join("\n");
  }

  lines.push("## How to Use");
  lines.push("");
  lines.push("1. Copy the prompt below into Claude, GitHub Copilot Chat, Gemini, or another LLM");
  lines.push("2. The AI will respond with only JSON");
  lines.push("3. Copy the AI's JSON response and save it as `ai-investigation.json`");
  lines.push("4. Re-run the analyzer with `--ai-investigation ai-investigation.json`");
  lines.push("");
  lines.push("The generated JSON will render in the HTML dashboard's AI Investigation section.");
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push("## Prompt");
  lines.push("");
  lines.push("Copy everything inside the code block below:");
  lines.push("");
  lines.push("```");
  lines.push(buildInvestigationJsonPrompt(analysis));
  lines.push("```");
  lines.push("");

  // Append the full analysis JSON for reference
  lines.push("---");
  lines.push("");
  lines.push("## Reference: Complete Deterministic Analysis");
  lines.push("");
  lines.push("The full analysis JSON is included below for manual reference.");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(buildAnalysisReference(analysis), null, 2));
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

/**
 * Build a compact reference JSON for the markdown appendix.
 */
function buildAnalysisReference(analysis) {
  return {
    summary: analysis.summary,
    statistics: analysis.statistics,
    results: (analysis.results || [])
      .filter(function (t) {
        return t.classification !== "stable_pass";
      })
      .map(function (t) {
        return {
          title: t.title,
          file: t.file,
          browser: t.browser,
          history: t.history,
          classification: t.classification,
          stabilityScore: t.stabilityScore,
          failureCategory: t.failureCategory,
          errors: (t.classifiedErrors || t.errors || []).map(function (e) {
            return typeof e === "string"
              ? { message: e }
              : { message: e.message, category: e.category };
          }),
        };
      }),
  };
}

module.exports = {
  buildAIInvestigationRequest,
  formatInvestigationPromptMd,
  formatInvestigationJsonPromptMd,
};
